services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=
      - SPRING_JPA_HIBERNATE_DIALECT=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=
      - SPRING_JPA_SHOW_SQL=
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=
