services:
  app:
    build: .
    ports:
      - "8008:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/hsautocars

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"