services:
  app:
    build: .
    ports:
      - "8008:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/hsautocars

  mongo:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - config/.env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - config/.env
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD:${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL:mongodb://root:example@mongo:27017/
      - ME_CONFIG_BASICAUTH:false